### ISSUE TITLE
Error running Sample app

### ISSUE THREAD

**Issue by praveenkrjha** [welegan/RedisSessionProvider#24]
I have issues running the Sample app that has been provided. I below error 

```
2016-02-09 15:02:42.1379 SampleUsageMVCApp.MvcApplication Unhandled RedisSessionProvider exception
System.MissingMethodException: Method not found: 'System.Nullable`1<Int32> StackExchange.Redis.ConfigurationOptions.get_DefaultDatabase()'.
   at RedisSessionProvider.Redis.RedisConnectionWrapper..ctor(String connIdentifier, ConfigurationOptions connOpts)
   at RedisSessionProvider.RedisSessionStateStoreProvider.RedisConnWrapperFromContext(HttpContextBase context) in RedisSessionStateStoreProvider.cs:line 463
   at RedisSessionProvider.RedisSessionStateStoreProvider.SerializeToRedis(HttpContextBase context, RedisSessionStateItemCollection redisItems, String currentRedisHashId, TimeSpan expirationTimeout) in RedisSessionStateStoreProvider.cs:line 374
   at RedisSessionProvider.RedisSessionStateStoreProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem) in RedisSessionStateStoreProvider.cs:line 302
```

I didn't change the code except for changing the Redis IP address.

**Comment by shakoorattari** [comment]
I'm also facing same issue.
any solution?
